### ISSUE TITLE
Ability to run on private custom models?

### ISSUE THREAD

**Issue by kossnick** [google-research/task_adaptation#3]
I understand this repo requires the input model to be hosted on tensorflow hub. It seems like all [tensorflow hub models must also be public](https://www.tensorflow.org/hub/hosting). Is there any way to run this on private hosted or local models? When working on new model architectures, it would be great to be able to use this as an evaluation tool. Thank you!

**Comment by akolesnikoff** [comment]
Not necessarily: the input model can be a local model that is saved as hub module. It is generally easy to export any trained tensorflow model as hub model, see https://www.tensorflow.org/hub/tf1_hub_module#creating_a_new_module as a starting point.

Feel free to reopen this issue if you have further questions.
